// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjFvY3_6JZwD7m1aSzYuQQsjrmDHHQnSg',
    appId: '1:518707307236:web:f218ab597dc5f8e5ef82f1',
    messagingSenderId: '518707307236',
    projectId: 'gemini-hack-e47e4',
    authDomain: 'gemini-hack-e47e4.firebaseapp.com',
    storageBucket: 'gemini-hack-e47e4.firebasestorage.app',
    measurementId: 'G-VD92CZKZSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFDw2OPhHiKzFPmFt5JSc69jzftpfY9Jk',
    appId: '1:518707307236:android:383e632db01546d8ef82f1',
    messagingSenderId: '518707307236',
    projectId: 'gemini-hack-e47e4',
    storageBucket: 'gemini-hack-e47e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFExumWeM1FkezG_GgteUabEpFk_Yrb6w',
    appId: '1:518707307236:ios:7a9bc1bff731ef2eef82f1',
    messagingSenderId: '518707307236',
    projectId: 'gemini-hack-e47e4',
    storageBucket: 'gemini-hack-e47e4.firebasestorage.app',
    iosClientId: '518707307236-5hqmvhde9f14a4amdjjvbirocn1rcq7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.finwise',
  );
}
